### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by jhough10** [thisbythem/stag#2]
Using the command-line for deploying and clearing cache is great. However, the one issue that I am having is that no matter what command I run it will always ask for my password. For example, I setup a sample deployment to sites staging environment and ran into some issues because it will request that I type my password for each step in the process which is upwards of 10+ times for each deployment I have tried to run. 

I figured it might be my configuration file (structure is below), but no matter how many times I have tried to mess with the configuration file it will continually request my password to be typed at each and every step. The deployment works flawlessly when I check the files after it is complete, but having to type my password that many times seems to defeat the purpose of using the command-line.

Any ideas on what it happening? I am currently on Dreamhost now, but I haven't had issues before using rsync over ssh before.

```
servers: 
  staging:
    host: example.com
    webroot: /var/www/example.com
    user: ******
    password: ******
    port: 22
    forward_agent: false
    strategy: rsync

    deploy:
      pull_content_before: true
      clear_cache_after: true
      set_permissions_after: true
      ignore_files:
        - .git
        - _cache
        - _logs

    pull_content:
      content_directories:
       - _content
       - assets
```
